<a href="https://colab.research.google.com/github/a-forty-two/cylons/blob/master/06_TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
# What's a node? https://www.electronics-tutorials.ws/dccircuits/kirchhoffs-current-law.html

# TENSORFLOW can draw both Directed, Non-Directed, and both CYclic and Acylcic graphs!
# it's a math library not a NN library! We are only using TF to get our obectives! 

# There are dedicated ML libs for NN /DL -> Theano, PyTorch 
tf.__version__

'2.2.0-rc3'

In [1]:
%tensorflow_version 1.x
import tensorflow as tf
print(tf.__version__)
# THINK of this as R,G,B pixels representing an image
inputs = [[200,0,1],[215,70,4],[0,0,200],[5,40,230]] 
# this was a problem statement to detect if a PIXEL is RED 
outputs = [ [1], [1], [0], [0] ]
# red, red, no-red, no-red 
# convert inputs into tensors 
trainingInputs = tf.convert_to_tensor(value=inputs, dtype=tf.int8) # 8 bits represent a number!
trainingInputs

TensorFlow 1.x selected.
1.15.2


<tf.Tensor 'Const:0' shape=(4, 3) dtype=int8>

In [2]:
# EVERY TENSORFLOW execution is supposed to RUN inside a TENSORFLOW SESSION only
# JUST LIKE DB session -> OPEN, OPERATE, CLOSE 
sessions = tf.Session()
x = sessions.run(fetches=trainingInputs)
print(x)
sessions.close()

# please resume by 11:55 

[[-56   0   1]
 [-41  70   4]
 [  0   0 -56]
 [  5  40 -26]]


In [0]:
# In order to BUILD DAGs, TF provides with 
# 1) CONSTANTS -> CONSTANT throughout the lifecycle
# 2) PLACEHOLDERS -> ARE EMPTY RESERVED SPACES FOR INPUTS and OUTPUTS. Placeholders' value
#        doesn't change in-between execution! 
# 3) VARIABLES -> VALUES which keep changing inside execution-> LEARNING -> WEIGHTS and BIASES 

In [0]:
import tensorflow
trainingInputs = tf.placeholder(shape=[None, 3], dtype=tf.float32)
trainingOutputs = tf.placeholder(shape=[None, 1], dtype=tf.float32)
weights = tf.Variable(initial_value=[[0.3],[0.1],[0.7]], dtype=tf.float32) # RANDOM, no logic
# y = x1w1 + x2w2 + x3w3 + bias 
bias = tf.Variable(initial_value=[[0.05]], dtype=tf.float32)
# these values have been RANDOMLY initialized! 


In [5]:
# FIRST build the graph nodes 
y = tf.matmul(trainingInputs, weights) + bias # y=mx + c
predictions = tf.nn.sigmoid(y)  # SIGMOID -> takes numbers, and converts them into a PROB func
# as a result output is between 0 and 1 
loss = tf.reduce_sum(trainingOutputs-predictions) # MAE 
HP_lr = 0.05
optimizer = tf.train.GradientDescentOptimizer(learning_rate=HP_lr).minimize(loss)
# optimizer reduces the LOSS! 
loss

# THIS IS A STANDALONE NN layer -> THIS IS NOT A NETWORK
# SINGLE LAYERs will be exactly same as MACHINE LEARNING with GT! 
# DEEP LEARNING means at least 3 such LAYERS! 

# THIS IS JUST A GRAPH NODE-> IT WILL NOT EXECUTE TILL YOU ACTUALLY RUN A SESSION! 

<tf.Tensor 'Sum:0' shape=() dtype=float32>

In [8]:
session = tf.Session()
session.run(tf.global_variables_initializer()) # THIS IS THE FIRST INITIALIZATION
# MUST, shouldn't/cannot/mustn't be skipped
inputs = [[200,0,1],[215,70,4],[0,0,200],[5,40,230]] 
# this was a problem statement to detect if a PIXEL is RED 
outputs = [ [1], [1], [0], [0] ]
for step in range(1000): # 1000 times -> LOSS will calc, opt will reduce it, and y calc again!
  session.run(fetches=[optimizer], feed_dict={trainingInputs:inputs, trainingOutputs:outputs})

print(session.run(weights))
print(session.run(bias))
# SCORING the model
print(session.run(fetches=predictions, feed_dict={trainingInputs:[[0,0,200],[1,200,200],[1,50,200]]}))

session.close()

[[0.3]
 [0.1]
 [0.7]]
[[0.05]]
[[1.]
 [1.]
 [1.]]


AFTER PRINTING weights and biases, we just realized that they are STILL the same values that we provided!!! THAT MEANS NO LEARNING HAPPENED!!



In [0]:
# ALL tf code only RUNS inside TENSORFLOW SESSION 

# LAZY EVALUATION
# BIG Data (Apache Spark, Data Bricks) and GRAPH libraries (TENSORFLOW) building ACYCLIC GRAPHS
# WHICH SHOULD ONLY be executed only all the info is known

# a = 1, b=2, c=a+b, print(c)
# normal programming language                           Tensorflow/ApacheSpark/DAG

# a=1, what is value of a? Lang = 1!                 a=1, what is value of a? TF = ok!
# b=2, what is value of b? Lang = 2!                 b=2, what is value of b? TF = ok!
# c = a+b, what is value of C? Lang = 3!             c = a+b, what is value of C? TF =ok! 
# print(c), printed, Language-> 3                     print(c) -> Now TF needs to know the value
#                                                     DAG will be built and executed 

