<a href="https://colab.research.google.com/github/a-forty-two/cylons/blob/master/09_Pooling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# AVERAGE -> special layer called GloablAveragePooling1D 

# each word broken into 3 vectors
# w1 -> v1 v2 v3   v1:|A|  np.mean(v1:3)
# w2 -> v4 v5 v6   v2 |1|
# w3 -> v7 v8 v9   v3 |D|   


In [1]:
%tensorflow_version 1.x
import tensorflow as tf
print(tf.__version__)

TensorFlow 1.x selected.
1.15.2


In [3]:
# totally randomly 
temp = [0.,0.,1.,0.,0.,0.,2.,1.,0.,1.]
values = tf.reshape(temp, [1,1,2,5]) # 1 list-> 1 list -> 2 list -> 5 elements each 
values
# TF SESSION! 

<tf.Tensor 'Reshape_1:0' shape=(1, 1, 2, 5) dtype=float32>

In [0]:
avgpool = tf.nn.pool(input=values, window_shape=(2,2), pooling_type='AVG', padding='SAME')
maxpool = tf.nn.pool(input=values, window_shape=(2,2), pooling_type='MAX', padding='SAME')

# PADDING anywhere means what to add in empty space! 
# in keras as a function -> SEQUENCES.PADDING 
#  [ 2, 2]  and [1] -> to make them both same, padding='same' -> [2, 2] and [1, 1]


In [8]:
# these were nodes of DAG until the TF.SESSION is run! 

session = tf.Session()
print('Original Data before reshaping')
print(temp)
print('Original Data after reshaping')
print(session.run(values))
print('AvgPool')
print(session.run(avgpool))
print('MaxPool')
print(session.run(maxpool))
session.close()


Original Data before reshaping
[0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 2.0, 1.0, 0.0, 1.0]
Original Data after reshaping
[[[[0. 0. 1. 0. 0.]
   [0. 2. 1. 0. 1.]]]]
AvgPool
[[[[0.  1.  1.  0.  0.5]
   [0.  2.  1.  0.  1. ]]]]
MaxPool
[[[[0. 2. 1. 0. 1.]
   [0. 2. 1. 0. 1.]]]]


In [0]:
# valid -> no padding 
avgpool2 = tf.nn.pool(input=values, window_shape=(1,2), pooling_type='AVG', padding='VALID')
maxpool2 = tf.nn.pool(input=values, window_shape=(1,2), pooling_type='MAX', padding='VALID')

In [16]:
session = tf.Session()
print('Original Data before reshaping')
print(temp)
print('Original Data after reshaping')
print(session.run(values))
print('AvgPool')
print(session.run(avgpool2))
print('MaxPool')
print(session.run(maxpool2))
session.close()
# FIRST TIME -> Padding was same -> 2X2 -> elements were missing, so same elements were added!

# [1,2] -> padding made it [1,2],[1,2] -> hence average become 1+2 +1 +2 / 4
# in second case -> it was 1 + 2 / 2

Original Data before reshaping
[0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 2.0, 1.0, 0.0, 1.0]
Original Data after reshaping
[[[[0. 0. 1. 0. 0.]
   [0. 2. 1. 0. 1.]]]]
AvgPool
[[[[0.  1.  1.  0.  0.5]]]]
MaxPool
[[[[0. 2. 1. 0. 1.]]]]


In [0]:
# valid -> no padding 
avgpool2 = tf.nn.pool(input=values, window_shape=(1,2), pooling_type='AVG', padding='VALID')
maxpool2 = tf.nn.pool(input=values, window_shape=(1,2), pooling_type='MAX', padding='VALID')

In [18]:
session = tf.Session()
print('Original Data before reshaping')
print(temp)
print('Original Data after reshaping')
print(session.run(values))
print('AvgPool')
print(session.run(avgpool2))
print('MaxPool')
print(session.run(maxpool2))
session.close()

Original Data before reshaping
[0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 2.0, 1.0, 0.0, 1.0]
Original Data after reshaping
[[[[0. 0. 1. 0. 0.]
   [0. 2. 1. 0. 1.]]]]
AvgPool
[[[[0.  1.  1.  0.  0.5]]]]
MaxPool
[[[[0. 2. 1. 0. 1.]]]]


In [0]:
# Data Structures: Mark Allen Weiss 
# https://www.careercup.com/page?pid=data-structures-interview-questions
